package com.mine.geometry_node.client.model.render.integration;

/** Stable fidelity codes emitted by compatibility projections. */
public enum ModelCompatibilityLoss {
    METALLIC_ROUGHNESS_APPROXIMATED,
    METALLIC_ROUGHNESS_UNREPRESENTABLE,
    METALLIC_UNREPRESENTABLE,
    ROUGHNESS_APPROXIMATED,
    ROUGHNESS_UNREPRESENTABLE,
    NORMAL_TEXTURE_APPROXIMATED,
    OCCLUSION_TEXTURE_APPROXIMATED,
    EMISSIVE_TEXTURE_APPROXIMATED,
    LABPBR_SHADERPACK_CONSUMPTION_UNVERIFIED,
    PROJECTOR_RUNTIME_UNAVAILABLE,
    PROJECTOR_HOLDER_PENDING,
    NORMAL_TEXTURE_UNREPRESENTABLE,
    OCCLUSION_TEXTURE_UNREPRESENTABLE,
    EMISSIVE_TEXTURE_UNREPRESENTABLE,
    INDEPENDENT_UV_UNREPRESENTABLE,
    TEXTURE_TRANSFORM_UNREPRESENTABLE,
    TEXTURE_SAMPLER_APPROXIMATED,
    ALPHA_CUTOFF_APPROXIMATED,
    SINGLE_SIDED_TRANSLUCENCY_UNREPRESENTABLE,
    TRANSPARENT_ORDERING_APPROXIMATED,
    ENTITY_TRANSLUCENCY_FALLBACK_OPAQUE,
    BLEND_SHADOW_APPROXIMATED,
    SIDED_NORMAL_APPROXIMATED,
    TEXTURE_DECODE_FAILED,
    GEOMETRY_PROJECTION_FAILED,
    MISSING_NORMALS_GENERATED,
    SINGULAR_TRANSFORM_REJECTED,
    GPU_SKINNING_UNREPRESENTABLE
}
